name: recipe_book_ai
description: 'A new Flutter project.'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  localstore: ^1.4.0
  flutter_speed_dial: ^7.0.0
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.10+1
  flutter_platform_alert: ^0.6.1
  duration_picker: ^1.2.0
  textfield_tags: ^3.0.1
  provider: ^6.1.2
  nanoid: ^1.0.0
  flutter_pannable_rating_bar: ^2.7.2+1
  searchable_listview: ^2.15.2
  dropdown_button2: ^2.3.9
  flutter_gemini: ^2.0.5
  flutter_dotenv: ^5.2.1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/svg/
    - .env
