name: recipe_book_ai
description: 'A new Flutter project.'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  localstore: ^1.4.0
  flutter_speed_dial: ^7.0.0
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.10+1
  flutter_platform_alert: ^0.6.1
  duration_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/svg/
